### ISSUE TITLE
[EPIC] Python Reader

### ISSUE THREAD

**Issue by xuchen-plus** [meta-soul/LakeSoul#201]
This is a tracking issue for LakeSoul's Python Reader. Python reader could read data in LakeSoul (including MOR and CDC tables) without relying on PySpark.

We'll implement the reader through Arrow DataFusion. We need to implement
- [ ] Metadata read and parse in Rust
- [ ] DataFusion CatalogProvider for LakeSoul
- [ ] DataFusion SchemaProvider for LakeSoul
- [ ] DataFusion TableProvider for LakeSoul
 

So that LakeSoul itself would become a datafusion source. And we could use datafusion's python binding to read data from LakeSoul as datafusion's dataframe which can be converted to pandas dataframe, pyarrow table and polars dataframe.
